script:
        - export VERSION=0.$TRAVIS_BUILD_NUMBER
        - export ARTIFACT=plugin.video.kodiver.wizjatv.$VERSION.zip
        - sed -i.bak s/VERSION/$VERSION/g bintray-deploy.json
        - zip -9 -r --exclude=*.idea* --exclude=*.gitignore* --exclude=*.git* --exclude=.travis.yml $ARTIFACT ../plugin.video.kodiver.wizjatv

deploy:
        provider: bintray
        file: bintray-deploy.json
        user: "gregmaslowski"
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on: master
