language: bash

before_install:
        - sudo apt-get update
        - sudo apt-get -qq install xmlstarlet

script:
        - export VERSION=0.$TRAVIS_BUILD_NUMBER
        - export ARTIFACT=plugin.video.kodiver.wizjatv-$VERSION.zip
        - sed -i.bak s/VERSION/$VERSION/g addon.xml
        - sed -i.bak s/VERSION/$VERSION/g bintray-deploy.json
        - sed -i.bak s/ZIP.ARTIFACT/$ARTIFACT/g bintray-deploy.json
        - cd .. 
        - zip -9 -r --exclude=*.idea* --exclude=*.gitignore* --exclude=*.git* --exclude=*.travis.yml* --exclude=*.json* --exclude=*.bak* plugin.video.kodiver.wizjatv/$ARTIFACT plugin.video.kodiver.wizjatv
        - cd plugin.video.kodiver.wizjatv/
        - git clone git://github.com/kodiver/repository.kodiver.git
        - cp addon.xml repository.kodiver/plugin-addon.xml
        - cd repository.kodiver
        - xmlstarlet ed -d "/addons/addon[@id='plugin.video.kodiver.wizjatv']" addons.xml > addons2.xml
        - xmlstarlet sel -R -t -c / -c "document('addons2.xml')" plugin-addon.xml | xmlstarlet ed -m /xsl-select/addon /xsl-select/addons | xmlstarlet sel -t -c /xsl-select/* - | xmlstarlet fo
        - rm -rf addons.xml
          rm -rf plugin-addon.xml
        - mv addons2.xml addons.xml
        - git add addons.xml
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git commit -m "Bump to newest plugin.video.kodiver.wizjatv ${VERSION}"
        - git push https://${GITHUB_TOKEN}@github.com/kodiver/repository.kodiver.git master

deploy:
        provider: bintray
        file: bintray-deploy.json
        user: "gregmaslowski"
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on: master
