script:
        - export VERSION = 0.$TRAVIS_BUILD_NUMBER
        - export ARTIFACT = plugin.video.kodiver.wizjatv.$VERSION.zip
        - zip -9 -r --exclude=*.idea* --exclude=*.gitignore* --exclude=*.git* --exclude=.travis.yml $ARTIFACT ../plugin.video.kodiver.wizjatv

